### ISSUE TITLE
Support checklist

### ISSUE THREAD

**Issue by vanurag** [vanurag/InfiniTAM#1]
- [x] calibration files for realsense and vi-sensor
- [x] dynamic reconfigure params for vi-sensor
- [x] stereo dense recon independency for vi-sensor
- [x] IMU sourceEngine for sensor-rig - from VI-Sensor

**Comment by vanurag** [comment]
Addressed in PR #2
